name: Build and Deploy
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Install latex
        run: |
            sudo apt-get update -y
            sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

      - name: Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: .
          pre-build-command: |
            pip install rinohtype
            cp _static/__init__.py /usr/local/lib/python3.8/site-packages/rinoh/language
            cp _static/bg.py /usr/local/lib/python3.8/site-packages/rinoh/language
          build-command: "make html"
        
      - name: Deploy HTML
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: _build/html
            SINGLE_COMMIT: true
        
      - name: Deploy PDF
        if: false
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: pdfs
            FOLDER: _build/rinoh
            SINGLE_COMMIT: true
